---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReadyNASUser:
    Type: AWS::IAM::User
    Properties:
      UserName: readynas
  CloudwatchLogsWriterPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudwatchLogsWriterPolicy
      Users:
        - Ref: ReadyNASUser 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - logs:DescribeLogStreams
          Resource:
          - arn:aws:logs:*:*:*
  S3BackupsWriterPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3BackupsWriter
      Users:
        - Ref: ReadyNASUser 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: 0
          Effect: Allow
          Action:
          - s3:*
          Resource:
          - arn:aws:s3:::davidspittlebackups
          - arn:aws:s3:::davidspittlebackups/*
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/var/log/s3-backup.log"
      RetentionInDays: 14
  S3BackupErrorMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "error"
      LogGroupName:
        Ref: LogGroup
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: LogMetrics
          MetricName: s3-backup-error
  ErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: AlarmsSNSTopic
      AlarmName: s3-backups errors
      EvaluationPeriods: 1
      Statistic: Sum
      MetricName: s3-backup-error
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      TreatMissingData: missing
      AlarmDescription: The s3 backups script has encountered an error. Please check the logs.
      Period: 300
      Namespace: LogMetrics
  NoLogsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: AlarmsSNSTopic
      AlarmName: s3-backups no logs
      EvaluationPeriods: 2
      Statistic: Sum
      MetricName: IncomingLogEvents
      ComparisonOperator: LessThanThreshold
      Threshold: 20
      TreatMissingData: breaching
      AlarmDescription: The s3 backups script has encountered an error. Please check the logs.
      Period: 3600
      Namespace: AWS/Logs
      Dimensions:
        - Name: LogGroupName
          Value:
            Ref: LogGroup
  AlarmsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: s3-backups-alarms
  AlarmsJustinSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: justin@dray.be
      Protocol: email
      TopicArn: 
        Ref: AlarmsSNSTopic 