---
- hosts: ReadyNAS01
  vars:
    ansible_pull_repo: git@github.com:justin8/davidspittle
    ansible_pull_playbook: "{{ ansible_pull_workdir }}/ansible/playbooks/david.yml"
  roles:
    - role: ansible-pull
