---
- hosts: ReadyNAS01
  vars:
    s3_backup_bucket: davidspittlebackups
    s3_backup_schedule: daily
    s3_backup_folder_root: /data
    s3_backup_folders:
      - /PROJECTS_NAS
      - /dave_nas
      - /Dave_words
      - /Library_Dave
      - /Photos_Dave
  roles:
    - role: s3-backup
  tasks:
    - name: copy awslogs.conf
      template:
        src: awslogs.conf.j2
        dest: /var/awslogs/etc/awslogs.conf
      notify: restart awslogs

  handlers:
    - name: restart awslogs
      service:
        name: awslogs
        state: restarted
